test = {   'name': 'q2b',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': '>>> q2b_part1 in set(["Quantitative Continuous", "Quantitative Discrete", \n...                   "Qualitative Ordinal", "Qualitative Nominal"])\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> q2b_part2 in set(["str", "int", "bool", "float"])\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
